version: '3.8'

services:
  # 1. PostgreSQL Database Container
  db:
    image: postgres:15-alpine
    container_name: hms_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: hospital_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/schema.sql

  # 2. FastAPI Application Container
  web:
    build: .
    container_name: hms_fastapi
    restart: always
    ports:
      - "8000:8000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgrespassword
      DB_NAME: hospital_db
      JWT_SECRET: supersecret_hms_jwt_key_2026_change_in_prod
    depends_on:
      - db

volumes:
  postgres_data: